chrdev_user_interface: chrdev_user_interface.o
	gcc -o chrdev_user_interface chrdev_user_interface.o

chrdev_user_interface.o: chrdev_user_interface.c
	gcc -c chrdev_user_interface.c

clean:
	rm -rf *.o chrdev_user_interface
